resolver: clash-HEAD.yaml

extra-deps:
  - barbies-2.0.1.0
  - barbies-th-0.1.2
  - monad-supply-0.9

  - constraints-extras-0.3.0.2
  - dependent-sum-0.7.1.0
  - dependent-map-0.4.0.0

packages:
  - '.'

ghc-options:
  dependent-map: -fexpose-all-unfoldings -fno-worker-wrapper
  mtl: -fexpose-all-unfoldings -fno-worker-wrapper
  transformers: -fexpose-all-unfoldings -fno-worker-wrapper
