resolver: lts-17.2

extra-deps:
  - barbies-2.0.1.0
  - barbies-th-0.1.2
  - monad-supply-0.9

  - constraints-extras-0.3.0.2
  - dependent-sum-0.7.1.0
  - dependent-map-0.4.0.0
  - some-1.0.1

  - arrows-0.4.4.2
  - Stream-0.4.7.2
  - lazysmallcheck-0.6
  - hedgehog-1.0.4
  - tasty-hedgehog-1.0.1.0

  - clash-compiler-HEAD/clash-lib
  - clash-compiler-HEAD/clash-ghc
  - clash-compiler-HEAD/clash-prelude

flags:
    clash-prelude:
      multiple-hidden: false

packages:
  - '.'

ghc-options:
  dependent-map: -fexpose-all-unfoldings -fno-worker-wrapper
  mtl: -fexpose-all-unfoldings -fno-worker-wrapper
  transformers: -fexpose-all-unfoldings -fno-worker-wrapper
