resolver: lts-16.21

extra-deps:
  - barbies-2.0.1.0
  - barbies-th-0.1.2
  - monad-supply-0.9

  - constraints-extras-0.3.0.2
  - dependent-sum-0.7.1.0
  - dependent-map-0.4.0.0

  - concurrent-supply-0.1.8
  - ghc-typelits-extra-0.4.1
  - clash-compiler-HEAD/clash-lib
  - clash-compiler-HEAD/clash-ghc
  - clash-compiler-HEAD/clash-prelude

flags:
    clash-prelude:
      multiple-hidden: false

packages:
  - '.'

ghc-options:
  dependent-map: -fexpose-all-unfoldings -fno-worker-wrapper
  mtl: -fexpose-all-unfoldings -fno-worker-wrapper
  transformers: -fexpose-all-unfoldings -fno-worker-wrapper
